CREATE DATABASE Erg_1_3792;
USE Erg_1_3792;

-- Erotima 1:
CREATE TABLE EMPLOYEES (
    FNAME VARCHAR(15) NOT NULL,
    LNAME VARCHAR(15) NOT NULL,
    SSN CHAR(7) NOT NULL,
    PRIMARY KEY (SSN)
); 
 SHOW CREATE TABLE EMPLOYEES;
 
-- Erotima 2:
ALTER TABLE EMPLOYEES 
	ADD COLUMN ADDRESS VARCHAR(40) NULL;
ALTER TABLE EMPLOYEES 
	ADD COLUMN ADDRESS2 VARCHAR(40) NULL;
ALTER TABLE EMPLOYEES 
	ADD COLUMN SALARY INT;
SHOW CREATE TABLE EMPLOYEES;
 
-- Erotima 3:
ALTER TABLE EMPLOYEES 
	DROP COLUMN ADDRESS2;
ALTER TABLE EMPLOYEES 
	MODIFY COLUMN ADDRESS VARCHAR(250) NULL;
ALTER TABLE EMPLOYEES 
	MODIFY COLUMN SALARY DECIMAL(10,2) NULL;
SHOW CREATE TABLE EMPLOYEES;

-- Erotima 4:
CREATE TABLE DEPARTMENTS (
    DNUMBER INT NOT NULL,
    DSSN CHAR(7) NOT NULL,
    DNAME VARCHAR(30) NOT NULL,
    PRIMARY KEY (DNUMBER)
);

 ALTER TABLE DEPARTMENTS
 ADD CONSTRAINT department_infk_1
 FOREIGN KEY (DSSN)
 REFERENCES EMPLOYEES(SSN);

 SHOW CREATE TABLE DEPARTMENTS;
 
 -- Erotima 5:
ALTER TABLE DEPARTMENTS DROP FOREIGN KEY department_infk_1;	-- Prepei prota na svisoume tin sisxetisi metaksi ton 2 pinakon
DROP TABLE EMPLOYEES; -- kai epeita mporoume na svisoume ton pinaka EMPLOYEES
SHOW TABLES;

-- Erotima 6:
CREATE TABLE EMPLOYEES (
    SSN CHAR(7) NOT NULL,
    DNO INT NOT NULL,
    PRIMARY KEY (SSN)
);

 ALTER TABLE EMPLOYEES
 ADD CONSTRAINT employees_infk_1
 FOREIGN KEY (DNO)
 REFERENCES DEPARTMENTS(DNUMBER);

SHOW TABLES;
SHOW CREATE TABLE EMPLOYEES;
 
-- Erotima 7:
ALTER TABLE EMPLOYEES DROP FOREIGN KEY employees_infk_1; -- Prepei prota na svisoume tin sisxetisi metaksi ton 2 pinakon
ALTER TABLE EMPLOYEES DROP COLUMN DNO; -- kai epeita mporoume na svisoume tin grammmi DNO (dioti xrisimopoihtai san kseno klidi)
SHOW CREATE TABLE EMPLOYEES;

-- Erotima 8:
CREATE TABLE PROJECTS (
    DNUMBER CHAR(7) NOT NULL,
    PRIMARY KEY (DNUMBER)
);
 SHOW CREATE TABLE PROJECTS;

CREATE TABLE Work_On (
    SSN CHAR(7) NOT NULL,
    DNUMBER CHAR(7) NOT NULL,
    PRIMARY KEY (SSN , DNUMBER),
    FOREIGN KEY (SSN)
        REFERENCES EMPLOYEES (SSN),
    FOREIGN KEY (DNUMBER)
        REFERENCES PROJECTS (DNUMBER)
);
 SHOW CREATE TABLE Work_On;